datasets:
  test:
    name: 'celeba-hq'
    batch_size: 1
    use_shuffle: False
    n_workers: 1
    fineSize: 256
    img_shape: [3, 256, 256]
    image_list: 'datasets/celeba-hq/list_val.txt'
    mask_list: 'datasets/mask/list.txt'
    mask_type: 'regular'
    mask_pos: 'random'
    mask_height: 128
    mask_width: 128
    vertical_margin: 0
    horizontal_margin: 0
    max_delta_height: 0
    max_delta_width: 0


network_G:
  which_model_G: 'DMFN'
  in_nc: 4
  out_nc: 3
  nf: 64
  n_res: 8