name: anycost
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - pytorch=1.7.1
  - torchvision=0.8.2
  - pillow=8.1.0
  - numpy=1.19.2
  - scipy=1.6.1
  - tqdm=4.56.0
  - notebook=6.2.0
  - ipywidgets=7.6.3
  - matplotlib=3.3.4
  - pip:
    - dlib==19.21.1
    - lpips==0.1.3
    - torchprofile==0.0.2
    - pyqt5==5.15.2
    - horovod==0.21.3
    - tensorboard==2.4.1
